-- Rooms pick a capture pipeline by id (b<kbps>-s<percent>, generated by the
-- worker) instead of a fixed high/medium/low quality. SQLite cannot drop a
-- CHECK constraint, so the table is rebuilt. '' = neko's default stream.
CREATE TABLE rooms_new (
    name             TEXT    PRIMARY KEY,
    access           TEXT    NOT NULL DEFAULT 'public'
                     CHECK (access IN ('public', 'account', 'verified', 'invite')),
    hidden           INTEGER NOT NULL DEFAULT 0,
    remote_ownership INTEGER NOT NULL DEFAULT 0,
    center_remote    INTEGER NOT NULL DEFAULT 0,
    default_remote   INTEGER NOT NULL DEFAULT 0,
    default_image    INTEGER NOT NULL DEFAULT 0,
    default_upload   INTEGER NOT NULL DEFAULT 0,
    screen           TEXT    NOT NULL DEFAULT '',
    stream           TEXT    NOT NULL DEFAULT ''
);

INSERT INTO rooms_new (name, access, hidden, remote_ownership, center_remote,
                       default_remote, default_image, default_upload, screen, stream)
SELECT name, access, hidden, remote_ownership, center_remote,
       default_remote, default_image, default_upload, screen,
       CASE quality WHEN 'high' THEN 'b4000-s100' WHEN 'low' THEN 'b1000-s67' ELSE '' END
FROM rooms;

DROP TABLE rooms;
ALTER TABLE rooms_new RENAME TO rooms;
